source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'mysql2'

group :development do
  gem 'pry', require: false
  gem 'awesome_print', require: false
end

group :development, :test do
  gem 'rspec-rails', '2.9.0'
  gem 'capybara'
  gem 'database_cleaner', '0.8.0'
end

group :test do
  gem 'factory_girl'
  gem 'factory_girl-preload'
end