source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'mysql2'

group :development do
  gem 'pry', require: false
  gem 'awesome_print', require: false
end

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
end